spring:
  application:
    name: dubbo-demo-provider
dubbo:
  application:
    name: dubbo-demo
    qos-enable: true
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    serialization: hessian2
server:
  port: 8888